---
name: Static Checks - Go

on:
  pull_request:
    paths:
      - '**/go.*'
      - '**.go'

concurrency:
  group: static-checks-go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-go-module:
    name: Check Go Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Test
        run: make go-test

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
