---
name: Static Checks - Go

on:
  push:
    branches:
      - main
    paths:
      - '**/go.*'
      - '**.go'
  pull_request:
    paths:
      - '**/go.*'
      - '**.go'

concurrency:
  group: static-checks-go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-go-module:
    name: Check Go Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: make go-test

      - name: Vet
        run: make go-vet

      - name: Staticcheck
        run: make go-staticcheck
